# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XCFrameworkConsumer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XCFrameworkConsumer
#  pod 'QuestionProCXFramework', :git => 'https://github.com/surveyanalyticscorp/ios-cx.git', :tag => '2.2.3'
#  pod 'QuestionProCXFramework', :git => 'https://github.com/prasad-bhide-qp/cxsdk', :tag => '2.2.3'
end
